export const SELECT_SEQUENCE = 'SELECT_SEQUENCE';
export const SEQUENCE_NEXT_VALUE = 'SEQUENCE_NEXT_VALUE';
export const ACTIVATE_SEQUENCE = 'ACTIVATE_SEQUENCE';
export const SELECT_PIPELINE = 'SELECT_PIPELINE';
